updated

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -41,7 +41,8 @@ jobs:
          npm install --save react react-dom @types/react @types/react-dom
          npm install react-scripts@3.0.1  --save
          npm install
-         #npm audit fix 
+         # Attempt to fix vulnerabilities, but continue if it fails
+         RUN npm audit fix --force || echo "Continuing despite npm audit fix failures"
 
     - name: Build container image
       run: docker build -t ${{ secrets.REGISTRY_NAME }}/bank-app-frontend:${{ github.run_number }} .
